# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

plugins=(
    git
    virtualenv
    vscode
    kubectl
    zsh-syntax-highlighting
)

# SOURCES
source $ZSH/oh-my-zsh.sh

# ALIASES
#source ~/.aliases

source {{ dotfiles_user_home }}/.zsh.d/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
eval "$(starship init zsh)"

