---

- name: setup local
  shell: |
    locale-gen en_US.UTF-8
  become: true
  become_user: root
  become_method: sudo

- name: Install cooker
  shell: |
    python -m pip install --upgrade git+https://github.com/cpb-/yocto-cooker.git
  tags: user