---

- name: install vscode server
  shell: |
    curl -fsSL https://code-server.dev/install.sh | sh
    mkdir -p $HOME/.vscode-server/extensions
  tags: user

- name: Install vscode server extension
  shell: |
    code-server --extensions-dir $HOME/.vscode-server/extensions --install-extension "{{ item }}"
  loop:
    - jebbs.plantuml
    - numaru.vscode-ceedling-test-adapter@v1.9.1
    - ms-vscode.cpp-tools
    - ms-vscode.cmake-tools
    - twxs.cmake
    - rust-lang.rust
    - ms-python.python
    - golang.go
    - premparihar.gotestexplorer
    - ms-azuretools.vscode-docker
    - gruntfuggly.todo-tree
  tags: user

# - name: Install ceedling extension
#   shell: |
#     wget https://github.com/numaru/vscode-ceedling-test-adapter/releases/download/v1.9.1/vscode-ceedling-test-adapter-1.9.1.vsix
#     code-server --extensions-dir ~/.vscode-server/extensions --install-extension vscode-ceedling-test-adapter-1.9.1.vsix
#   tags: user