---


- name: Install ceedling
  shell: |
    gem install ceedling
  become: true
  become_user: root
  become_method: sudo

- name: Install Gcovr
  shell: |
    python -m pip install --upgrade gcovr
  tags: user